[package]
name = "example01-static-elf-snapshot"
version = "0.1.0"
edition = "2024"

[dependencies]
libafl = "0.15.3"
libafl_bolts = "0.15.3"
lief = "0.17.2"
valkyrie-rs = { path = "../../../../", features = ["libafl"] }

[profile.fuzz]
inherits = "release"
opt-level = 3
lto = "thin"
codegen-units = 1
incremental = false
debug = 0
