[package]
name = "valkyrie-rs"
version = "1.0.0"
edition = "2024"
description = "Rust binary emulator"
license = "Apache"
readme = "README.md"
authors = ["0xMirasio"]

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
thiserror = "1"
unicorn-engine = { version = "2.1.4", features = ["dynamic_linkage"] }
capstone="0.13.0"
udbserver= { path = "external/udbserver" }
libc = "0.2.180"