afl_out=/home/titip/valkyrie-rs/examples/fuzzing/example01/afl_out
queue=/home/titip/valkyrie-rs/examples/fuzzing/example01/afl_out/queue
crash=/home/titip/valkyrie-rs/examples/fuzzing/example01/afl_out/crash
config=/home/titip/valkyrie-rs/examples/fuzzing/example01/afl_out/config
state=/home/titip/valkyrie-rs/examples/fuzzing/example01/afl_out/state
state_interval=10000
