name: Rust CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo test
        run: cargo test --all --locked

      - name: Build release library artifacts
        run: cargo build --release --locked

      - name: Upload valkyrie library
        uses: actions/upload-artifact@v4
        with:
          name: valkyrie-libs
          path: target/release/libvalkyrie_rs.so
